---
title: "R Notebook"
output: html_notebook
---

Source: http://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays/

    
```{r}
# compile the C code
system("R CMD SHLIB ../src/array_plus_one.c")
```


```{r}
# this loads the library in any system, Windows or Linux
dyn.load(paste("../src/array_plus_one", .Platform$dynlib.ext, sep = ""))

# wrapper
arrayPlus1 = function(m) {
   m[] = .C('arrplus1', as.numeric(m), dim(m))[[1]]
   m
}

arrayPlus1(array(1, dim = c(4,5,3)))

dyn.unload(paste("../src/array_plus_one", .Platform$dynlib.ext, sep = ""))
```

```{r}
# passing an array
matrixPlus1(array(1, dim = c(3,4,2)))

# only the first array gets added because in C we are only have two loops:
# one loop per dimension
# , , 1
# 
#      [,1] [,2] [,3] [,4]
# [1,]    2    2    2    2
# [2,]    2    2    2    2
# [3,]    2    2    2    2
#
# , , 2
# 
#      [,1] [,2] [,3] [,4]
# [1,]    1    1    1    1
# [2,]    1    1    1    1
# [3,]    1    1    1    1
```


## changing the loop to three dimensions

```{r}
# http://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays/

library(inline)

sig <- signature(x="numeric", dim="integer")

body3 <- "
    #include <stdio.h>
    for (int i = 0; i < dim[0]; ++i)
        for (int j = 0; j < dim[1]; ++j)
            for (int k = 0; k < dim[2]; ++k) {
                x[ k + dim[2]*(j+ i*dim[1]) ] += 1;
            }
        
"

cfun3 <- cfunction(sig, body=body3, language="C", convention=".C")

# using the C function in R
plus3 <- function(m) {
    m[] = cfun3(as.numeric(m), dim(m))$x
    m
}

plus3(array(1, dim = c(3, 4, 3)))
```


```{r}
# applying on a vector 3x1x1
plus3(array(1, dim = c(3, 1, 1)))
```










