---
title: "R Notebook"
output: html_notebook
---


```{r}
require(Rcpp)
require(inline)


src <- '
#include <RcppArmadillo.h>

// [[Rcpp::depends(RcppArmadillo)]]
using namespace Rcpp; 
using namespace arma;

// [[Rcpp::export]]
mat cubeMeans(arma::cube X){
   int nSlice = X.n_slices;
   int nCol = X.n_cols;
   int nRow = X.n_rows;

   arma::vec Vtmp(nCol);
   arma::mat Mtmp(nRow, nCol);
   arma::mat Means(nCol, nSlice);
   for (int i = 0; i < nSlice; i++){
      Mtmp = X.slice(i);
      for(int j = 0; j < nCol; j++){
         Vtmp(j) = sum(Mtmp.col(j)) / nRow; 
      }
      Means.col(i) = Vtmp;
   }
  return(Means);
}
'
cppFunction(code=src, depends="RcppArmadillo")

xl <- array(1:10e4, c(20, 10 ,10))
cubeMeans(xl)
```


## column means of a cube

Source: https://stackoverflow.com/a/30981930/5270873

```{r}
# https://stackoverflow.com/a/30981930/5270873
require(Rcpp)
require(inline)

src <- '

arma::mat cube_means(Rcpp::NumericVector vx) {

  Rcpp::IntegerVector x_dims = vx.attr("dim");
  arma::cube x(vx.begin(), x_dims[0], x_dims[1], x_dims[2], false);

  arma::mat result(x.n_cols, x.n_slices);
  for (unsigned int i = 0; i < x.n_slices; i++) {
    result.col(i) = arma::conv_to<arma::colvec>::from(arma::mean(x.slice(i)));  
  }

  return result;
}
'

#/*** R

cppFunction(code=src, depends="RcppArmadillo")

# R equivalent function
rcube_means <- function(x) t(apply(x, 2, colMeans))

xl <- array(1:10e5, c(100, 100 ,10))
all.equal(rcube_means(xl), cube_means(xl))

# benchmarking
microbenchmark::microbenchmark(
    "R Cube Means" = rcube_means(xl),
    "Arma Cube Means" = cube_means(xl),
    times = 200L)
```

