---
title: "R Notebook"
output: html_notebook
---


```{r}

src <- '
    Rcpp::NumericVector yr(ys);
    Rcpp::NumericMatrix Xr(Xs);
    int n = Xr.nrow(), k = Xr.ncol();
    
    arma::mat X(Xr.begin(), n, k, false);
    arma::colvec y(yr.begin(), yr.size(), false);
    
    arma::colvec coef = arma::solve(X, y);              // fit y ˜ X
    arma::colvec res = y - X*coef; // residuals
    
    double s2 = std::inner_product(res.begin(), res.end(),
                                        res.begin(),double())
                                         / (n - k);
    arma::colvec se = arma::sqrt(s2 *
                        arma::diagvec(arma::inv(arma::trans(X)*X)));
    
    return Rcpp::List::create(Rcpp::Named("coef")= coef,
                              Rcpp::Named("se") = se,
                              Rcpp::Named("df") = n-k);
'

fun <- cxxfunction(signature(ys="numeric", Xs="numeric"), 
                   src, 
                   plugin="RcppArmadillo")

## could now run fun(y, X) to regress y ˜ X   


```

```{r}
# provide a matrix for group
lm.plugin <- fun(weight, group)
lm.plugin
```



```{r}
## Annette Dobson (1990) "An Introduction to Generalized Linear Models".
## Page 9: Plant Weight Data.
ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
group <- gl(2, 10, 20, labels = c("Ctl","Trt"))
weight <- c(ctl, trt)
lm.D9 <- lm(weight ~ group)
lm.D90 <- lm(weight ~ group - 1) # omitting intercept
lm.D9
```

